
http:
  port: 8080
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  username: "postgres"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  password: "qwerty"
  sslmode: "disable"